"""empty message

Revision ID: e34cd0928450
Revises: 
Create Date: 2023-12-30 23:46:32.744380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e34cd0928450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autos')
    op.drop_table('personas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Apellido', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Sexo', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('autos',
    sa.Column('Marca', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Modelo', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Año', mysql.INTEGER(display_width=4), autoincrement=False, nullable=False),
    sa.Column('Motor', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
