"""Creación de la tabla Personas

Revision ID: fbf0b4a67b01
Revises: e34cd0928450
Create Date: 2024-01-01 06:30:00.084230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fbf0b4a67b01'
down_revision: Union[str, None] = 'e34cd0928450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    # ### end Alembic commands ###
